### PR TITLE
Addition from Riccardo De Leo

### PR DESCRIPTION
**Pull request by rdeleo**
Enjoy!

### CODE REVIEW

**Comment by francescomalatesta** [comment]
Wooah :) Thank you @rdeleo , just a feedback before merging it: can you adhere to the contribution guidelines I specified? Probably you forked the repo an hour ago, or maybe two.  You totally removed the entire document (with the index) and replaced it with the previous version. :)

Thanks!

**Comment by rdeleo** [comment]
Maybe you're checking only the edited file and for this reason you cannot see the untouched one :)

**Comment by francescomalatesta** [comment]
[This](https://github.com/francescomalatesta/weekend-learning/pull/1/commits/25032fdd552febcbfe5c5c44761f2d7875412140) is what I see, I can't merge it :)

Edit: if you can, rebase this repo to the last version and then add the contributions... we will solve it faster

**Comment by rdeleo** [comment]
Oh silly me ! I'm sorry , I did another push in my repo, please check it !

**Comment by francescomalatesta** [comment]
Some other feedbacks here and there:
- no link for the Phalcon entry! Where I am supposed to start?
- many suggested items are just showing a link to the official docs. Where is the "quick adoption" factor? Yeah, many technologies requires time, but the point of this repository is to find something that can facilitate its adoption (like quickstarts);
- the Slim3 demo is just a demo. See the Laravel related link to get an idea of a good getting started example;
- if possible, try to add recent links. Yeah, many old articles are good, but I am not sure that nothing good about testing was written since 2013;

As I told you before, rebase this repo to the latest version and then add your contribute... thanks :)

**Comment by rdeleo** [comment]
I have a better idea my friend, I deleted my fork, if u want add what u want by ourself and have fun founding better documentation. 

Bye !

**Comment by francescomalatesta** [comment]
Lol, you proposed those changes, it's up to you :) I just suggested you how to follow the repo guidelines... have a nice day!

**Pull request closed without merging**
