### PR TITLE
HAL and Git-flow

### PR DESCRIPTION
**Pull request by savez**
HAL and Git-flow

### CODE REVIEW

**Comment by francescomalatesta** [comment]
Hello @savez , thanks for your PR. I just ask you a little fix before merging it.

I like the git-flow add, but imho it's not a very strict "fundamental". Could you add it under "Tools" and create a new subcategory named "Versioning"?

Because everyone uses git nowadays (I hope lol), but not git-flow after all :)

Thank you!

**Comment by francescomalatesta** [comment]
Oh, and check the output format :) some descriptions are not _italic_ :)

**Comment by savez** [comment]
changes made

**Comment by francescomalatesta** [comment]
Thank you for your patience :) merging it! :+1:

**Pull request merged**
